version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '80:80'